#include "compile_time_sha1.hpp"
#include "compile_time_sha224.hpp"
#include "compile_time_sha256.hpp"
#include "compile_time_sha384.hpp"
#include "compile_time_sha512.hpp"
#include "compile_time_sha512_256.hpp"
#include "compile_time_md5.hpp"
